package by.sichnenko.committee.command;

enum CommandEnum {
    //***COMMON***
    MAIN,
    SIGN_IN,
    SIGN_UP,
    CHANGE_LOCALE,
    SHOW_DETAIL_FACULTY,
    SHOW_SIGN_IN_PAGE,
    SHOW_SIGN_UP_PAGE,
    SHOW_ENROLLEES_BUDJET,
    SHOW_ENROLLEES_PAID,
    FIND_SUBJECTS_BY_FACULTY,
    FIND_CITIES_BY_COUNTRY_ID,

    //***USER***
    FILL_ENROLLEE,
    SIGN_OUT,
    CHANGE_PASSWORD,
    CHANGE_AVATAR,
    EDIT_ENROLLEE,
    EDIT_USER_PROFILE,
    SHOW_MY_PROFILE_PAGE,
    SHOW_EDIT_PROFILE_PAGE,
    SHOW_ENROLLEE_FILL_PAGE,
    SHOW_CHANGE_PASSWORD_PAGE,
    SHOW_EDIT_ENROLLEE,

    //***ADMIN***
    CHANGE_USER_LOCK,
    CHANGE_USER_ROLE,
    ADD_NEW_FACULTY,
    LOAD_FACULTY_IMAGE,
    ADD_COUNTRY,
    ADD_CITY,
    SHOW_ALL_USERS,
    SHOW_DETAIL_USER,
    SHOW_USERS_BY_STATUS,
    SHOW_ADD_FACULTY_PAGE,
    SHOW_ADD_CITY_PAGE,
    SHOW_ADD_COUNTRY_PAGE,
    CHANGE_ENROLLEE_STATUS,
    ENROLL,
    ENROLL_TO_FACULTY,
    //*********************
}
