package by.sichnenko.committee.command;

enum CommandEnum {
    EMAIL_SEND,
    MAIN, FILE_LOAD,
    SIGN_IN, SIGN_UP,
    FILL_ENROLLEE,
    CHANGE_LOCALE,
    SIGN_OUT,
    SHOW_ENROLLEE_FILL_PAGE,
    SHOW_ALL_USERS,
    SHOW_DETAIL_USER,
    CHANGE_USER_LOCK,
    CHANGE_USER_ROLE,
    SHOW_USERS_BY_STATUS,
    SHOW_DETAIL_FACULTY,
    SHOW_CHANGE_PASSWORD_PAGE,
    CHANGE_PASSWORD,
    SHOW_ADD_FACULTY_PAGE,
    ADD_NEW_FACULTY,
    FIND_CITIES_BY_COUNTRY_ID,
    LOAD_FILE,
    LOAD_FACULTY_IMAGE,
    CHANGE_ALL_ENROLLEE_STATUS,
    CHANGE_ENROLLEE_STATUS,
    CHANGE_AVATAR
}
